name: oscars
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  csv: ^6.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/data/oscar_songs.csv
    - assets/data/oscar_winner.csv
    - assets/data/oscar_nominee.csv
    
