// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/oscar_winner.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8232101523916932536),
    name: 'OscarWinner',
    lastPropertyId: const obx_int.IdUid(14, 1276799510603434446),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7275728714612782847),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7455885821653834255),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7807431662019575191),
        name: 'winner',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1156532430112520825),
        name: 'yearFilm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3549273356804532246),
        name: 'yearCeremony',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5199642120994688846),
        name: 'ceremony',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3918805087392333084),
        name: 'canonCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2990807629759252016),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1276799510603434446),
        name: 'film',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8232101523916932536),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2361008182485471480,
      1062957096206510594,
      4291117618097005060,
      762299298102777391,
      5497574396884656749,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    OscarWinner: obx_int.EntityDefinition<OscarWinner>(
      model: _entities[0],
      toOneRelations: (OscarWinner object) => [],
      toManyRelations: (OscarWinner object) => {},
      getId: (OscarWinner object) => object.id,
      setId: (OscarWinner object, int id) {
        object.id = id;
      },
      objectToFB: (OscarWinner object, fb.Builder fbb) {
        final categoryOffset = fbb.writeString(object.category);
        final canonCategoryOffset = fbb.writeString(object.canonCategory);
        final nameOffset = fbb.writeString(object.name);
        final filmOffset = fbb.writeString(object.film);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, categoryOffset);
        fbb.addBool(4, object.winner);
        fbb.addInt64(8, object.yearFilm);
        fbb.addInt64(9, object.yearCeremony);
        fbb.addInt64(10, object.ceremony);
        fbb.addOffset(11, canonCategoryOffset);
        fbb.addOffset(12, nameOffset);
        fbb.addOffset(13, filmOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final yearFilmParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final yearCeremonyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final ceremonyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final canonCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final filmParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final winnerParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = OscarWinner(
          yearFilm: yearFilmParam,
          yearCeremony: yearCeremonyParam,
          ceremony: ceremonyParam,
          category: categoryParam,
          canonCategory: canonCategoryParam,
          name: nameParam,
          film: filmParam,
          winner: winnerParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OscarWinner] entity fields to define ObjectBox queries.
class OscarWinner_ {
  /// See [OscarWinner.id].
  static final id = obx.QueryIntegerProperty<OscarWinner>(
    _entities[0].properties[0],
  );

  /// See [OscarWinner.category].
  static final category = obx.QueryStringProperty<OscarWinner>(
    _entities[0].properties[1],
  );

  /// See [OscarWinner.winner].
  static final winner = obx.QueryBooleanProperty<OscarWinner>(
    _entities[0].properties[2],
  );

  /// See [OscarWinner.yearFilm].
  static final yearFilm = obx.QueryIntegerProperty<OscarWinner>(
    _entities[0].properties[3],
  );

  /// See [OscarWinner.yearCeremony].
  static final yearCeremony = obx.QueryIntegerProperty<OscarWinner>(
    _entities[0].properties[4],
  );

  /// See [OscarWinner.ceremony].
  static final ceremony = obx.QueryIntegerProperty<OscarWinner>(
    _entities[0].properties[5],
  );

  /// See [OscarWinner.canonCategory].
  static final canonCategory = obx.QueryStringProperty<OscarWinner>(
    _entities[0].properties[6],
  );

  /// See [OscarWinner.name].
  static final name = obx.QueryStringProperty<OscarWinner>(
    _entities[0].properties[7],
  );

  /// See [OscarWinner.film].
  static final film = obx.QueryStringProperty<OscarWinner>(
    _entities[0].properties[8],
  );
}
